# Generated by Django 6.0.7 on 2026-07-28 11:53

from django.conf import settings
from django.db import migrations, models


def deduplicate_submissions(apps, schema_editor):
    """Keep only the most recent submission per (user, dish) pair."""
    RatingSubmission = apps.get_model("ratings", "RatingSubmission")
    seen = set()
    for submission in RatingSubmission.objects.order_by("user_id", "dish_id", "-created_at"):
        key = (submission.user_id, submission.dish_id)
        if key in seen:
            submission.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_francesinha_dish_type'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_submissions, migrations.RunPython.noop),
        migrations.AddField(
            model_name='ratingsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='ratingsubmission',
            unique_together={('user', 'dish')},
        ),
    ]
