# Generated by Django 6.0.7 on 2026-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_ratingsubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsubmission',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
