# Generated by Django 6.0.7 on 2026-07-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_venue_location_fields'),
        ('ratings', '0003_ratingsubmission_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsubmission',
            name='venue_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_submissions', to='catalog.venuelocation'),
        ),
    ]
