# Generated by Django 6.0.7 on 2026-08-07 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_ratingsubmission_venue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriatemplate',
            name='max_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=4),
        ),
    ]
