# Generated by Django 6.0.7 on 2026-08-07 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_criteriatemplate_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriatemplate',
            name='min_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.5'), max_digits=4),
        ),
    ]
