# Generated by Django 6.0.7 on 2026-07-30 13:52

from django.conf import settings
from django.db import migrations


def backfill_userprofiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model("accounts", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={"is_public": True})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_userprofiles, migrations.RunPython.noop),
    ]
