# Generated by Django 6.0.7 on 2026-07-27 15:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAggregateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_score', to='catalog.dish')),
            ],
            options={
                'ordering': ['-composite_score', '-rating_count', 'dish__name'],
            },
        ),
    ]
