# Generated by Django 6.0.7 on 2026-07-28 10:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishaggregatescore',
            options={'ordering': ['-avg_overall_score', '-rating_count', 'dish__name']},
        ),
        migrations.AddField(
            model_name='dishaggregatescore',
            name='avg_overall_score',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6),
        ),
    ]
