# Generated by Django 6.0.7 on 2026-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_venue_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='photo_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='photo_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo_source_url',
            field=models.URLField(blank=True),
        ),
    ]
