# Generated by Django 6.0.7 on 2026-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_saveddish'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google Places')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='business_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='google_maps_uri',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='google_user_rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='price_level',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='primary_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='venuelocation',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
