# Generated by Django 6.0.7 on 2026-08-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_dishtype_dish_saveddish_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitter_name', models.CharField(blank=True, max_length=120)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('search_query', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_from', to='catalog.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
