# Generated by Django 6.0.7 on 2026-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_venuesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuesuggestion',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
